name: github-g4predictor
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - alabaster=0.7.13
  - altgraph=0.17.3
  - arrow=1.3.0
  - astroid=3.0.1
  - asttokens=2.4.1
  - atomicwrites=1.4.1
  - attrs=23.1.0
  - autopep8=2.0.4
  - babel=2.13.1
  - bcrypt=4.1.1
  - beautifulsoup4=4.12.2
  - binaryornot=0.4.4
  - biopython=1.78
  - black=23.11.0
  - bleach=6.1.0
  - bottleneck=1.3.7
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - cairo=1.18.0
  - catboost=1.2.5
  - certifi=2024.7.4
  - cffi=1.16.0
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.2.0
  - cookiecutter=2.5.0
  - cryptography=41.0.7
  - cuda-version=12.3
  - cycler=0.12.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20230430
  - dill=0.3.7
  - docstring-to-markdown=0.13
  - docutils=0.20.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - flake8=6.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.47.2
  - freetype=2.12.1
  - fribidi=1.0.10
  - gettext=0.21.1
  - glib=2.78.3
  - glib-tools=2.78.3
  - graphite2=1.3.13
  - graphviz=9.0.0
  - gst-plugins-base=1.22.7
  - gstreamer=1.22.7
  - gts=0.7.6
  - harfbuzz=8.3.0
  - icu=73.2
  - idna=3.6
  - imagesize=1.4.1
  - importlib-metadata=7.0.0
  - importlib-resources=6.1.1
  - importlib_metadata=7.0.0
  - importlib_resources=6.1.1
  - inflection=0.5.1
  - intervaltree=3.1.0
  - ipykernel=6.26.0
  - ipython=8.18.1
  - isort=5.12.0
  - jaraco.classes=3.3.0
  - jedi=0.19.1
  - jellyfish=1.0.3
  - jinja2=3.1.2
  - joblib=1.3.2
  - jsonschema=4.20.0
  - jsonschema-specifications=2023.11.2
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyterlab_pygments=0.3.0
  - keyring=24.3.0
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libdeflate=1.19
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgd=2.3.3
  - libglib=2.78.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libogg=1.3.4
  - libopenblas=0.3.26
  - libpng=1.6.39
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libsqlite=3.44.2
  - libtiff=4.6.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxgboost=1.7.3
  - libxml2=2.12.2
  - libzlib=1.2.13
  - lightgbm=3.3.5
  - llvm-meta=5.0.0
  - logomaker=0.8
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib-base=3.8.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.0
  - mistune=3.0.2
  - more-itertools=10.1.0
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.12.0
  - nbconvert-core=7.12.0
  - nbconvert-pandoc=7.12.0
  - nbformat=5.9.2
  - nest-asyncio=1.5.8
  - nomkl=1.0
  - numexpr=2.8.8
  - numpy=1.26.3
  - numpydoc=1.6.0
  - openjpeg=2.5.0
  - openpyxl=3.1.4
  - openssl=3.2.1
  - packaging=23.2
  - pandas=2.1.1
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - pango=1.50.14
  - paramiko=3.3.1
  - parso=0.8.3
  - pathspec=0.12.1
  - pcre2=10.42
  - pefile=2023.2.7
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.1
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.1.0
  - plotly=5.18.0
  - pluggy=1.3.0
  - ply=3.11
  - prompt-toolkit=3.0.41
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-xgboost=1.7.3
  - pycodestyle=2.11.1
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyflakes=3.1.0
  - pygments=2.17.2
  - pyinstaller=6.9.0
  - pyinstaller-hooks-contrib=2024.7
  - pylint=3.0.2
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyparsing=3.1.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyqtwebengine=5.15.9
  - pysimplegui=4.60.5
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.0
  - python-graphviz=0.20.1
  - python-lsp-black=1.3.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.9.0
  - python-lsp-server-base=1.9.0
  - python-slugify=8.0.1
  - python-tzdata=2023.4
  - python_abi=3.9
  - pytoolconfig=1.2.5
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qdarkstyle=3.2
  - qstylizer=0.2.2
  - qt-main=5.15.8
  - qt-webengine=5.15.8
  - qtawesome=1.2.3
  - qtconsole=5.5.1
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - referencing=0.32.0
  - requests=2.31.0
  - rich=13.7.0
  - rope=1.11.0
  - rpds-py=0.13.2
  - rtree=1.1.0
  - scikit-learn=1.0.2
  - scipy=1.12.0
  - seaborn=0.12.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=7.2.6
  - sphinxcontrib-applehelp=1.0.7
  - sphinxcontrib-devhelp=1.0.5
  - sphinxcontrib-htmlhelp=2.0.4
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.6
  - sphinxcontrib-serializinghtml=1.1.9
  - spyder=5.5.0
  - spyder-kernels=2.5.0
  - sqlite=3.44.2
  - stack_data=0.6.2
  - tabulate=0.9.0
  - tenacity=8.2.3
  - text-unidecode=1.3
  - textdistance=4.5.0
  - threadpoolctl=3.2.0
  - three-merge=0.1.1
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.12.3
  - tornado=6.3.3
  - tqdm=4.66.4
  - traitlets=5.14.0
  - types-python-dateutil=2.8.19.14
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2023c
  - ujson=5.9.0
  - unicodedata2=15.1.0
  - urllib3=2.1.0
  - watchdog=3.0.0
  - wcwidth=0.2.12
  - webencodings=0.5.1
  - whatthepatch=1.0.5
  - wheel=0.42.0
  - xgboost=1.7.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.17
  - xorg-libxt=1.3.0
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yapf=0.40.1
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
